### ISSUE TITLE
Provide iso alpha 2 as well

### ISSUE THREAD

**Issue by hugolpz** [simonepri/country-iso#10]
Sources:
- https://github.com/moimikey/iso3166-1/blob/master/data/countries.json
- https://github.com/pde-rent/country_denomination/blob/master/country_denomination.json

**Comment by simonepri** [comment]
Hi hugolpz@ thanks for the suggestion!

At the moment I would probably avoid to bloat this package with additional conversions since there are already dedicated packages to go from alpha-3 to alpha-2.

But if there's a large demand then we can think about adding it (although I doubt).
