### ISSUE TITLE
extent for cities?

### ISSUE THREAD

**Issue by musicformellons** [simonepri/country-iso#7]
This looks very nice! Will try it in a project soon!

I was wondering: how difficult is it to extent this for cities? So results will be land & city (if any)?

**Comment by simonepri** [comment]
The big problem is that we have to map each relation on OpenStreetMap.
I've done it manually for the countries in the [osm-countries](https://github.com/simonepri/osm-countries) repo but doing it for every city is infeasible.

**Comment by musicformellons** [comment]
Yeah, I noticed. Great work! I looked around some time ago for a library that could go from coordinates to country (and city) name, but could not find anything close. Now you made it, thanks a lot!
